const LOGIN = 'LOGIN'
const SIGNUP = 'SIGNUP'
const LOGOUT = 'LOGOUT'
const SET_STUDENT = 'SET_STUDENT'
const ALL_HOMEWORKS = 'ALL_HOMEWORKS';

export { LOGIN, SIGNUP, LOGOUT, SET_STUDENT, ALL_HOMEWORKS };
