const LOGIN = 'LOGIN'
const SIGNUP = 'SIGNUP'
const LOGOUT = 'LOGOUT'
const SET_STUDENT = 'SET_STUDENT'
const SHOW_TEACHER = 'SHOW_TEACHER'
const SHOW_ALL_TEACHER = 'SHOW_ALL_TEACHER'

export { LOGIN, SIGNUP, LOGOUT, SET_STUDENT, SHOW_TEACHER, SHOW_ALL_TEACHER };
