const T_LOGIN = 'T_LOGIN';
const T_SIGNUP = 'T_SIGNUP';
const T_LOGOUT = 'T_LOGOUT';
const SET_TEACHER = 'SET_TEACHER';
const ADD_CARD = 'ADD_CARD';
const SHOW_STUDENTS = 'SHOW_STUDENTS';

export { T_LOGIN, T_SIGNUP, T_LOGOUT, SET_TEACHER, SHOW_STUDENTS, ADD_CARD };
